upstream flask {  
 server web:5000;
}

server {
    client_max_body_size 100M;

    #access_log /home/usuario/logs/access.log;
    #error_log /home/usuario/logs/error.log;

    proxy_read_timeout 240s;

    keepalive_timeout  100;

    listen 5000;
	listen [::]:5000;

    location / { 
        proxy_pass http://flask;

        #As proximas linhas passam o IP real para o gunicorn nao achar que sao acessos locais
        proxy_pass_header Server;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
    }
    
    # location /static/ {    
    #     autoindex on;    
    #     alias /static/; 
    # }

    # location /media/ {
    #     autoindex on;
    #     alias /media/;
    # }
}